/* Generated by Yosys 0.69+24 (git sha1 d0e71cfb7-dirty, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 15.2.1) */

(* top =  1  *)
(* src = "../rtl/top/icarus_gpu_top_yosys.sv:2.1-37.10" *)
module icarus_gpu_top(clk_sys, rst_n, s_axis_tvalid, s_axis_tready, s_axis_tdata, s_axis_tlast, m_axi_araddr, m_axi_arvalid, m_axi_arready, m_axi_rdata, m_axi_rvalid, m_axi_rready, m_axi_awaddr, m_axi_wdata, m_axi_wvalid, m_axi_wready, m_axi_bvalid, m_axi_bready, fb_valid, fb_x, fb_y
, fb_color, sensor_out);
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:6.16-6.23" *)
  input clk_sys;
  wire clk_sys;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:7.16-7.21" *)
  input rst_n;
  wire rst_n;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:8.33-8.46" *)
  input s_axis_tvalid;
  wire s_axis_tvalid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:9.33-9.46" *)
  output s_axis_tready;
  wire s_axis_tready;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:10.23-10.35" *)
  input [63:0] s_axis_tdata;
  wire [63:0] s_axis_tdata;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:11.33-11.45" *)
  input s_axis_tlast;
  wire s_axis_tlast;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:12.23-12.35" *)
  output [31:0] m_axi_araddr;
  wire [31:0] m_axi_araddr;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:13.33-13.46" *)
  output m_axi_arvalid;
  wire m_axi_arvalid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:14.33-14.46" *)
  input m_axi_arready;
  wire m_axi_arready;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:15.23-15.34" *)
  input [63:0] m_axi_rdata;
  wire [63:0] m_axi_rdata;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:16.33-16.45" *)
  input m_axi_rvalid;
  wire m_axi_rvalid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:17.33-17.45" *)
  output m_axi_rready;
  wire m_axi_rready;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:18.23-18.35" *)
  output [31:0] m_axi_awaddr;
  wire [31:0] m_axi_awaddr;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:19.23-19.34" *)
  output [63:0] m_axi_wdata;
  wire [63:0] m_axi_wdata;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:20.33-20.45" *)
  output m_axi_wvalid;
  wire m_axi_wvalid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:21.33-21.45" *)
  input m_axi_wready;
  wire m_axi_wready;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:22.33-22.45" *)
  input m_axi_bvalid;
  wire m_axi_bvalid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:23.33-23.45" *)
  output m_axi_bready;
  wire m_axi_bready;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:24.33-24.41" *)
  output fb_valid;
  wire fb_valid;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:25.33-25.37" *)
  output [15:0] fb_x;
  wire [15:0] fb_x;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:26.33-26.37" *)
  output [15:0] fb_y;
  wire [15:0] fb_y;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:27.33-27.41" *)
  output [31:0] fb_color;
  wire [31:0] fb_color;
  (* src = "../rtl/top/icarus_gpu_top_yosys.sv:28.23-28.33" *)
  output [31:0] sensor_out;
  wire [31:0] sensor_out;
  assign sensor_out = 32'd0;
  assign fb_color = 32'd0;
  assign fb_y = 16'h0000;
  assign fb_x = 16'h0000;
  assign fb_valid = 1'h0;
  assign m_axi_bready = 1'h1;
  assign m_axi_wvalid = 1'h0;
  assign m_axi_wdata = 64'h0000000000000000;
  assign m_axi_awaddr = 32'd0;
  assign m_axi_rready = 1'h1;
  assign m_axi_arvalid = 1'h0;
  assign m_axi_araddr = 32'd0;
  assign s_axis_tready = 1'h1;
endmodule
